const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('native', {
  onMenu: (fn) => ipcRenderer.on('menu', (_e, cmd) => fn(cmd)),
  openFigure: () => ipcRenderer.invoke('open-figure'),
  saveFigure: (args) => ipcRenderer.invoke('save-figure', args),
  pickImages: () => ipcRenderer.invoke('pick-images'),
  exportFile: (args) => ipcRenderer.invoke('export-file', args),
  exportPdf: (args) => ipcRenderer.invoke('export-pdf', args),
  fetchPdb: (id) => ipcRenderer.invoke('fetch-pdb', id),
  openPath: (p) => ipcRenderer.invoke('open-path', p),
  listPacks: () => ipcRenderer.invoke('list-packs'),
  readPackIcon: (pack, file) => ipcRenderer.invoke('read-pack-icon', { pack, file }),
  contextMenu: (items) => ipcRenderer.send('context-menu', items),
  pubchemLookup: (name) => ipcRenderer.invoke('pubchem-lookup', name),
  listVersions: (file) => ipcRenderer.invoke('list-versions', file),
  readVersion: (file, id) => ipcRenderer.invoke('read-version', { file, id }),
  watchFile: (file) => ipcRenderer.send('watch-file', file),
  onFileChanged: (fn) => ipcRenderer.on('file-changed', (_e, f) => fn(f)),
  readFile: (file) => ipcRenderer.invoke('read-file', file),
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  listFolder: (dir) => ipcRenderer.invoke('list-folder', dir),
  makeFolder: (dir, name) => ipcRenderer.invoke('make-folder', { dir, name }),
  reveal: (p) => ipcRenderer.invoke('reveal', p),
  listTemplates: () => ipcRenderer.invoke('list-templates'),
  saveTemplate: (t) => ipcRenderer.invoke('save-template', t),
  deleteTemplate: (f) => ipcRenderer.invoke('delete-template', f),
  exportTemplate: (t) => ipcRenderer.invoke('export-template', t),
  importTemplate: () => ipcRenderer.invoke('import-template'),
  onOpenFile: (fn) => ipcRenderer.on('open-file', (_e, r) => fn(r)),
  pendingOpen: () => ipcRenderer.invoke('pending-open'),
  pickFolderPath: () => ipcRenderer.invoke('pick-folder-path'),
  ttsVoices: () => ipcRenderer.invoke('tts-voices'),
  ttsExport: (a) => ipcRenderer.invoke('tts-export', a),
  gpuStatus: () => ipcRenderer.invoke('gpu-status'),
  packCatalog: () => ipcRenderer.invoke('pack-catalog'),
  installPack: (id) => ipcRenderer.invoke('install-pack', id),
  saveUserIcon: (icon) => ipcRenderer.invoke('save-user-icon', icon),
  deleteUserIcon: (file) => ipcRenderer.invoke('delete-user-icon', file),
  onPackProgress: (fn) => ipcRenderer.on('pack-progress', (_e, p) => fn(p)),
  copyImage: (dataUrl) => ipcRenderer.invoke('copy-image', dataUrl),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (s) => ipcRenderer.invoke('save-settings', s),
  aiGenerate: (req) => ipcRenderer.invoke('ai-generate', req),
  fetchImage: (url) => ipcRenderer.invoke('fetch-image', url),
});
