// Builds src/phylogroups.js: which everyday group (mammals, birds, insects, plants…) each PhyloPic image belongs to,
// so the library can show PhyloPic's ~4,500 clades under about 20 groups. Uses the public PhyloPic API.
// Usage: node scripts/phylogroups.js
const fs = require('fs'), path = require('path');

// Most specific first: an image goes in the first group whose clade contains it.
const GROUPS = [
  ['Birds', ['Aves']],
  ['Dinosaurs & pterosaurs', ['Dinosauria', 'Pterosauria']],
  ['Mammals', ['Mammalia']],
  ['Reptiles', ['Reptilia']],
  ['Amphibians', ['pan-Lissamphibia', 'Lissamphibia']],
  ['Fish & other vertebrates', ['Vertebrata']],
  ['Insects', ['Hexapoda']],
  ['Spiders, scorpions & mites', ['Chelicerata']],
  ['Crustaceans', ['Crustacea']],
  ['Other arthropods', ['Arthropoda']],
  ['Molluscs', ['Mollusca']],
  ['Worms', ['Annelida', 'Nematoda', 'Platyhelminthes', 'Nemertea']],
  ['Echinoderms & sea squirts', ['Echinodermata', 'Tunicata', 'Hemichordata', 'Amphioxidae']],
  ['Jellyfish, corals & sponges', ['Cnidaria', 'Ctenophora', 'Porifera', 'Placozoa']],
  ['Other animals', ['Metazoa']],
  ['Plants & algae', ['Viridiplantae', 'Archaeplastida', 'Rhodophyta']],
  ['Fungi', ['Fungi']],
  ['Bacteria', ['Eubacteria']],
  ['Protists & other life', ['Eukarya']],
];
const API = 'https://api.phylopic.org';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
async function getJson(url, tries = 4) {
  for (let i = 0; ; i++) {
    try {
      const r = await fetch(url, { redirect: 'follow', headers: { accept: 'application/vnd.phylopic.v2+json' } });
      if (!r.ok) throw new Error(`${r.status} ${url}`);
      return await r.json();
    } catch (e) { if (i >= tries) throw e; await sleep(800 * (i + 1)); }
  }
}
async function pool(list, fn, n = 6) {
  const out = new Array(list.length);
  let next = 0;
  await Promise.all(Array.from({ length: n }, async () => { while (next < list.length) { const i = next++; out[i] = await fn(list[i]); } }));
  return out;
}
const uuidOf = (href) => (href.match(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/) || [])[0];

(async () => {
  const build = (await getJson(`${API}/`)).build;
  console.log('build', build);
  const groupOf = new Map();
  for (const [group, clades] of GROUPS) {
    for (const name of clades) {
      const found = await getJson(`${API}/nodes?build=${build}&filter_name=${encodeURIComponent(name.toLowerCase())}&embed_items=true&page=0`);
      const node = ((found._embedded || {}).items || []).find((n) => (n._links.self.title || '').toLowerCase() === name.toLowerCase());
      if (!node) { console.log(`  ${name}: not found`); continue; }
      const id = uuidOf(node._links.self.href);
      const first = await getJson(`${API}/images?build=${build}&filter_clade=${id}`);
      const pages = await pool(Array.from({ length: first.totalPages || 0 }, (_, p) => p), (p) => getJson(`${API}/images?build=${build}&filter_clade=${id}&page=${p}`));
      let added = 0;
      for (const pg of pages) for (const it of pg._links.items || []) { const u = uuidOf(it.href); if (u && !groupOf.has(u)) { groupOf.set(u, group); added++; } }
      console.log(`  ${group} ← ${name}: ${first.totalItems} images, ${added} new`);
    }
  }
  // Compact: per group, the first 8 hex digits of each image id.
  const out = {};
  for (const [u, g] of groupOf) (out[g] = out[g] || []).push(u.slice(0, 8));
  const order = GROUPS.map(([g]) => g).filter((g) => out[g]);
  const body = order.map((g) => `  ${JSON.stringify(g)}: '${out[g].sort().join(' ')}',`).join('\n');
  const file = path.join(__dirname, '..', 'src', 'phylogroups.js');
  fs.writeFileSync(file, `// Generated by scripts/phylogroups.js from the PhyloPic API (build ${build}): the everyday group of each PhyloPic\n// image, keyed by the first 8 hex digits of its id. Images not listed go under "Other organisms".\nglobalThis.PHYLO_GROUPS = {\n${body}\n};\n`);
  console.log(`wrote ${file}: ${groupOf.size} images in ${order.length} groups`);
})().catch((e) => { console.error(e); process.exit(1); });
